### ISSUE TITLE
Option to set streambed roughness in config file

### ISSUE THREAD

**Issue by mtpain** [VirtualWatershed/CoRD#12]
Currently the [veg2n function](https://github.com/VirtualWatershed/CoRD/blob/master/cord/ripcas_dflow.py#L189) does not allow the user to set the streambed roughness. Can't use the BC n-value since that is streambed & floodplain average.

- [ ] enable this to be set in config file or as interactive param
- [ ] add parameter to [`veg2n`](https://github.com/VirtualWatershed/CoRD/blob/master/cord/ripcas_dflow.py#L189)

**Comment by mtpain** [comment]
@agregory65 can you please add the hydrologist explanation of the difference between the streambed roughness used in the boundary value calculation and the streambed roughness for the channel? What is the proper terminology for each?

**Comment by mtpain** [comment]
Here's a quick vis to confirm streambed vegmap values are zero

![jemez_vegmap](https://cloud.githubusercontent.com/assets/2425472/15791095/3d6829b8-298a-11e6-85fc-3690e653d705.png)

**Comment by agregory65** [comment]
Basically, the 0.04 roughness value is a weighted mannings for just the downstream BC(it includes channel and floodplain). Assigning a value to the entire channel is different because it is likely to have a greater overall impact on model results, the channel has a distinct roughness, and we can test the sensitivity of the model to changes in channel bed roughness.  I would like to have control over both but a good starting point for the channel only values is 0.035.

**Comment by mtpain** [comment]
Excellent, thanks for the explanation. There will be an option in the config file to set both :)  But the config file template will have these included.
